### ISSUE TITLE
Doesn't work with Sodium's custom interface

### ISSUE THREAD

**Issue by NebelNidas** [adamviola/BoostedBrightness#1]
I know this isn't your mod's problem, but maybe you could contact the developers and discuss about a better implementation on their side?

**Comment by adamviola** [comment]
Since Sodium replaces the video settings screen, there's not much we can do. It would take significant work on the author's part to change that for a small mod like Boosted Brightness. 

I can add keybinds to raise, lower, and reset brightness. What do you think of this solution?

**Comment by NebelNidas** [comment]
Looks like Sodium is going to provide an API for this in the future: https://github.com/jellysquid3/sodium-fabric/issues/414#issuecomment-739527013
Pull request: https://github.com/jellysquid3/sodium-fabric/pull/293

But until then, a keybinds solution would be fine I guess 👍

**Comment by Bstn1802** [comment]
Using Java Reflection you can manipulate almost everything (actually quite amazing and interesting what you can do with it)
Its a bit dirty but it works, here my pullrequest: https://github.com/adamviola/BoostedBrightness/pull/9
