### ISSUE TITLE
Using mod on 1.18 with sodium causes new "simulation distance" to be swapped with brightness

### ISSUE THREAD

**Issue by eaterofananas88** [adamviola/BoostedBrightness#21]
I've found that using sodium on 1.18 alongside this mod causes the simulation distance and brightness settings to be swapped in the video settings, so the simulation distance can be adjusted from -100 to 1200, and the brightness from 0 to 100.

**Comment by Bstn1802** [comment]
This has to do with the "old" sodium compatibility implementation which was selecting the slider by its position and not by its name. It was a pretty sketchy quick and dirty workaround bcs I didnt know better at that time, but I improved the sodium compatibilty a while ago and that should also fix this issue, its just that the owner hasn't merged that [pullrequest](https://github.com/adamviola/BoostedBrightness/pull/19) yet.

**Comment by LevMan7** [comment]
mod on 1.18 doesn't work?

**Comment by Bstn1802** [comment]
It should. Even for 1.18.1. It's just the bug mentioned above, for which there's already a fix, but the owner needs to merge and build himself to update the mod page. This will only affect you if you're using sodium and even then the mod should be usable, it might just be a bit complicated using the keybinds instead of the slider

**Comment by LevMan7** [comment]
> It should. Even for 1.18.1. It's just the bug mentioned above, for which there's already a fix, but the owner needs to merge and build himself to update the mod page. This will only affect you if you're using sodium and even then the mod should be usable, it might just be a bit complicated using the keybinds instead of the slider

should I wait for the release for 1.18+?.. will he? and how soon?

**Comment by adamviola** [comment]
Fixed! Sorry for the delay!
