### ISSUE TITLE
Incompatible with 1.19

### ISSUE THREAD

**Issue by ColonalKohler** [adamviola/BoostedBrightness#26]
Just here to report what happens on 1.19 if it helps development.

The game opens, and mod menu even detects the mod.
But when trying to edit the config the game crashes, either using mod menu or key binds.

> The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: field_1840
Exit Code: -1

With the removal of editing the gamma in the options.txt manually in 1.19, this mod would be very useful to content creators!

**Comment by adamviola** [comment]
[Updated to 1.19!](https://www.curseforge.com/minecraft/mc-mods/boosted-brightness)
