### ISSUE TITLE
1.19 support 

### ISSUE THREAD

**Issue by Yoad1704** [adamviola/BoostedBrightness#28]
Hi, I've been using this mod for a while and I want to use it on 1.19 so yeah any chance that it will be updated soon?
I'm aware that now you cant change the gamma above the limit so if it affects the mod I would understand if it will take longer but Im curious how much lo?

**Comment by adamviola** [comment]
1.19 version should be out by Tuesday!

**Comment by adamviola** [comment]
[Updated to 1.19!](https://www.curseforge.com/minecraft/mc-mods/boosted-brightness)
