### ISSUE TITLE
No negative Brightness/Gamma possible

### ISSUE THREAD

**Issue by LaidBackSloth** [adamviola/BoostedBrightness#30]
When setting the brightness to values below 0 in 1.19+, it just looks like 0. While porting the slider feature to forge, I found out the issue. It should be fixed by applying this mixin: https://github.com/LaidBackSloth/BetterBrightnessSlider/blob/forge-1.19.X/src/main/java/com/laidbacksloth/brightnessslider/mixin/LightTextureMixin.java, at least it does in forge, but I think fabric should be the same (you might need to add remap = true).

**Comment by adamviola** [comment]
Thanks for reporting this. Fixed in the 1.19.3 release.
