### ISSUE TITLE
1.19.3 Semi-incompatibility

### ISSUE THREAD

**Issue by R00tB33rMan** [adamviola/BoostedBrightness#33]
Boosted Brightness works almost fully; however, the game will crash if you attempt to open its settings UI or any related UIs. Keybinds and modifiers for this mod do work and do still increase/decrease brightness accordingly.

**Comment by Charles224488** [comment]
I have the same problem too

**Comment by Charles224488** [comment]
https://github.com/mvilk/BoostedBrightness/releases/tag/v2.1.3

**Comment by brickviking** [comment]
Thank you. This appears to fix the problem I had. I'm grateful for the work.

**Comment by adamviola** [comment]
Thanks guys! Mod has been officially updated.
