### ISSUE TITLE
Doesn't work with sildur's shaders

### ISSUE THREAD

**Issue by FatalCreations** [adamviola/BoostedBrightness#8]
Video wouldn't upload cuz bigger than 10mb
[Uploaded to yt instead](https://youtu.be/bVFYrB5EPfg)
idk if its a setting in the shader or not and am very dumb

edit: the first part of video with it working is with shaders set to off
another edit cuz line 3 above: with shaders on it does still effect the minimap tho

**Comment by adamviola** [comment]
Looks like Sildur's shaders don't use Minecraft's brightness slider. You can change the brightness settings of the shader via Video Settings > Shaders > Shader Options > Color.
